# Generated by Django 3.0.4 on 2020-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200314_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='jam_kehadiran_dosen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rata-Rata Jam Kehadiran Dosen'),
        ),
        migrations.AlterField(
            model_name='data',
            name='kelulusan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jumlah Lulusan Mahasiswa'),
        ),
        migrations.AlterField(
            model_name='data',
            name='peminat_prodi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Presentase % Peminat Prodi'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rerata_ipk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rerata IPK'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rerata_nilai_dosen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rata-Rata Nilai Dosen'),
        ),
    ]
