# Generated by Django 3.0.4 on 2020-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trainingnaivebayes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSvmSmo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('constant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Constant')),
                ('iterasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iterasi')),
                ('k_fold', models.CharField(blank=True, max_length=100, null=True, verbose_name='KFold (Split)')),
            ],
        ),
    ]
