# Generated by Django 3.0.4 on 2020-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200329_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('lamda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lambda')),
                ('sigma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigma')),
                ('constant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Constant')),
                ('gamma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gamma')),
                ('iterasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iterasi')),
            ],
        ),
    ]
