# Generated by Django 3.0.4 on 2020-06-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trainingsvmsmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsvmsmo',
            name='epsilon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Epsilon'),
        ),
    ]
