# Generated by Django 3.0.4 on 2020-05-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_training'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='TrainingSvmSeq',
        ),
    ]
