# Generated by Django 3.0.4 on 2020-06-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trainingdecissiontree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsvmseq',
            name='lamda',
        ),
        migrations.RemoveField(
            model_name='trainingsvmseq',
            name='sigma',
        ),
    ]
