# Generated by Django 3.0.4 on 2020-05-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200515_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsvmseq',
            name='k_fold',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KFold (Split)'),
        ),
    ]
