# Generated by Django 3.0.4 on 2020-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200627_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_mulai', models.CharField(blank=True, max_length=10, null=True, verbose_name='Semester Mulai')),
                ('kode_prodi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Prodi')),
                ('tahun_smstr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tahun Semester')),
                ('nama_prodi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Program Studi')),
                ('peminat_prodi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Presentase % Peminat Prodi')),
                ('rerata_ipk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rerata IPK')),
                ('kelulusan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jumlah Lulusan Mahasiswa')),
                ('jam_kehadiran_dosen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rata-Rata Jam Kehadiran Dosen')),
                ('rerata_nilai_dosen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rata-Rata Nilai Dosen')),
                ('label_kelas', models.CharField(blank=True, max_length=30, null=True, verbose_name='Label Kelas Prodi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
